In [5]:
import numpy as np

In [5]:
#Create a 1D array of integers from 1 to 10
a = np.array([1,2,3,4,5,6,7,8,9,10]) # or we can use a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
#Create a 2D array with random float values of shapes(3,4)
b = np.random.rand(3,4)
print(b)

[[0.86493072 0.98249441 0.7211095  0.88062635]
 [0.96949916 0.32212084 0.26530121 0.84244724]
 [0.29610831 0.28097791 0.49882    0.15746066]]


In [11]:
#Create a 3D array of zeros with shape(2,3,4)
c = np.zeros((2,3,4))
print(c)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [13]:
#Given two 1D arrays, performf element-wise addition, subtraction,multiplication and division
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
addition = np.add(a,b)
sub = np.subtract(a,b)
multiply = np.multiply(a,b)
division = np.divide(a,b)
print ("Addition", addition)
print("Substraction", sub)
print("Multiplication", multiply)
print("Division", division)

Addition [ 7  9 11 13 15]
Substraction [-5 -5 -5 -5 -5]
Multiplication [ 6 14 24 36 50]
Division [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [19]:
#Calculate the mean, median and standard deviation of a given 1D array
a = np.arange(1,11)
mean = np.mean(a)
median = np.median(a)
sd = np.std(a)
print("The original array is ",a)
print("The mean of the array is ",mean)
print("The median of the array is ",median)
print("The Standard Devviation is ",sd)

The original array is  [ 1  2  3  4  5  6  7  8  9 10]
The mean of the array is  5.5
The median of the array is  5.5
The Standard Devviation is  2.8722813232690143


In [27]:
#Reshape a 1D array into a 2D array of shape(3,4)
a = np.arange(1,13)
reshape = a.reshape((3,4))
print("The reshaped array is: \n",reshape)


The reshaped array is: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
#Extract the first row and last column of a 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
first_row = a[0,:]
print(first_row)

[1 2 3]


In [33]:
last_column= a[:,-1]
print(last_column)

[3 6 9]


In [35]:
#Reverse the order of element in 1D array.
reversed = a[::-1]
print(reversed)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [37]:
#Select elements form a 2D array that satisfy a specific condition(e.g., values 
#greater than a certain threshold)
t =5
b = a[a>t]
print("The elements are : ",b)

The elements are :  [6 7 8 9]


In [39]:
#Add a scalar value to each element of a 2D array
a = np.array([[1,2,3],[4,5,6]])
print("The original array is ",a)
added_array = a+5
print("The added value array is ",added_array)

The original array is  [[1 2 3]
 [4 5 6]]
The added value array is  [[ 6  7  8]
 [ 9 10 11]]


In [41]:
#Multiply a 1D array with a 2D array, leveraging numpy's broadcasting rules
b = np.array([1,2,3])
multiply = np.multiply(a,b)
print(multiply)

[[ 1  4  9]
 [ 4 10 18]]


In [7]:
#Calculate the dot product of two 1-dimensional arrays.
array1 = np.array([1, 2, 3]) 
array2 = np.array([4, 5, 6])
# Calculate the dot product
dot_product = np.dot(array1, array2)
print("Dot Product:", dot_product)

Dot Product: 32


In [11]:
#Compute the matrix multiplication of two 2-dimensional arrays.
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]]) 
# Compute the matrix multiplication
matrix_multiplication = np.dot(matrix1, matrix2) 
print("Matrix Multiplication:\n",matrix_multiplication)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [13]:
#Find the inverse and determinant of a square matrix.
square_matrix = np.array([[1, 2], [3, 4]]) 
# Calculate the inverse 
inverse_matrix = np.linalg.inv(square_matrix) 
print("Inverse Matrix:\n", inverse_matrix) 
# Calculate the determinant 
determinant = np.linalg.det(square_matrix) 
print("Determinant:", determinant)

Inverse Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
